modelog: debug

postgresdb:
  host: "0.0.0.0"
  port: 5432
  user: "admin"
  password: "admin"
  name: "home-service"

redisdb:
  host: "localhost:6379"
  port: 6379
  name: "name"

grpc:
  port: 9002
  authaddress: "localhost:9001"

jet:
  addres: "localhost:4222"
  subject: "house"
  name: "subscriber"